import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Breadcrumbs from "../components/Breadcrumbs";
import React, { useEffect } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LTU Tab Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const studentNumber = "21993608";
  const studentName = "Steph Newland";

  useEffect(() => {
    console.log(`[${new Date().toISOString()}] App loaded`);
    console.log(
      `Student Name: ${studentName}, Student Number: ${studentNumber}`
    );
  }, []);

  return (
    <html lang="en">
      <body
        /*className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen text-gray-900 dark:text-gray-100 transition-colors duration-300`}*/
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen bg-gray-100 dark:bg-gray-900 text-gray-900 dark:text-gray-100 transition-colors duration-300`}
      >
        <Header studentNumber={studentNumber} />

        {/* Full-width container for breadcrumbs */}
        <div className="w-full px-4 py-2">
          <Breadcrumbs />
        </div>

        <main className="flex-grow">{children}</main>

        <Footer studentName={studentName} studentNumber={studentNumber} />
      </body>
    </html>
  );
}
